### ISSUE TITLE
Explore cloud services

### ISSUE THREAD

**Issue by zmtbnv** [umartokyo/Lexis#1]
Research pros/cons of:
1. Google Cloud
2. Microsoft Azure
3. AWS

**Comment by umartokyo** [comment]
> I have joined the waitlist for bard after coming home, and I already got the access 🤩

Here's what I've got: 
### Google Cloud Run
* **Pros**:
	* Easy to use
	* Cost-effective
	* Scalable
	* Secure
* **Cons**:
	* Limited features
	* Not as mature as AWS or Azure
### Amazon AWS
* **Pros**:
	* Wide range of features
	* Mature platform
	* Scalable
	* Secure
* **Cons**:
	* Can be complex to use
	* Not as cost-effective as Google Cloud Run
### Microsoft Azure
* **Pros**:
	* Wide range of features
	* Mature platform
	* Scalable
	* Secure
* **Cons**:
	* Can be complex to use
	* Not as cost-effective as Google Cloud Run

> I have checked the information through other sources of information and this looks like true.
> I think that in this situation, using Google Cloud Run would be the most beneficial for us. 
> These are some reasons:
1. You're more familiar to it
2. It has a more friendly UI
3. It's easier and faster to learn then other two
4. It's cheaper
