### ISSUE TITLE
Understand how unit tests are done in Python

### ISSUE THREAD

**Issue by zmtbnv** [umartokyo/Lexis#4]
- [x] Why testing is important? Short answer: https://imsadra.me/unit-testing-in-python-and-best-practices#heading-2-why-testing
- [x] Explore how to test python code with `unittest` module: [Watch unit test intro](https://www.youtube.com/watch?v=6tNS--WetLI),   [skim throu Unittest module docs](https://docs.python.org/3/library/unittest.html) and read [A Beginner’s Guide to Unit Tests in Python](https://www.dataquest.io/blog/unit-tests-python/)
- [x] Understand how Python object Mock for unit test works: https://www.youtube.com/watch?v=xT4SV7AH3G8
- [x] Learn about Unit testing for Python database applications: https://igeorgiev.eu/python/tdd/python-unittest-database-applications/

**Comment by umartokyo** [comment]
Thank you very much! These sources were very helpful!
