### ISSUE TITLE
I figured out what Lexis meant! 

### ISSUE THREAD

**Issue by umartokyo** [umartokyo/Lexis#5]
@zmtbnv, "Lexis" is derived from the Greek word λέξις, which translates to "speech", "word" or "diction" in English. It is commonly used in linguistics to refer to the vocabulary of a language or a particular speaker or group of speakers. While lexis is a data visualization project of a keyword search.

**Comment by zmtbnv** [comment]
Interesting. It became popular around 1980s according to:
![image](https://user-images.githubusercontent.com/22429559/236653374-3120e849-0b31-46a7-a391-27922331f0ab.png)
