### ISSUE TITLE
Port Error in Google Cloud Run.

### ISSUE THREAD

**Issue by umartokyo** [umartokyo/Lexis#6]
Good evening Azamat Aka @zmtbnv , how are you doing?

For third day, I am trying to deploy my flask container to the cloud, and there is one error which I can't fix. Can you help me please. 
This is the error I'm constantly getting after deploying a service in a google cloud run:

`he user-provided container failed to start and listen on the port defined provided by the PORT=5000 environment variable. Logs for this revision might contain more information. Logs URL: https://console.cloud.google.com/logs/viewer?project=lexis-385407&resource=cloud_run_revision/service_name/lexispleasework/revision_name/lexispleasework-00002-jab&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22lexispleasework%22%0Aresource.labels.revision_name%3D%22lexispleasework-00002-jab%22 For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start`

Locally, the docker image and container it creates works perfectly when I give any port, but I get this error when uploading my docker to the cloud run. 

I will be learning about unit tests while waiting for your reply, thank you!

**Comment by zmtbnv** [comment]
Sorry for late reply.
In the **Container, Networking, Security** second we have **Container Port** field. That where your container's exposed port (in your case its 5000) should match. 

You can do either:
1. Change default Cloud Run port from 8080 to 5000
2. Or change your container's port from 5000 to 8080.

I hope this should fix 👍🏻 

![image](https://user-images.githubusercontent.com/22429559/236653268-4091f966-1cc3-414a-b117-33b13e949c77.png)

**Comment by umartokyo** [comment]
Good afternoon Azamat Aka. 
I too thought that this is the error, and tried to fix it earlier by changing the ports both to 5000 and when it didn't work both to 8080. It feels like I've tried everything, but it doesn't seem to want to work. 

Right now, while writing this, I discovered that there's some error with apple silicon Macs, and found one article which might help. [This one](https://medium.com/geekculture/from-apple-silicon-to-heroku-docker-registry-without-swearing-36a2f59b30a3)

I will read through the article, and then share the result soon

**Comment by umartokyo** [comment]
IT WORKED!
I AM SO HAPPY 😁

The whole error was happening because of the architecture which docker image was being compiled for. (Google Cloud services run on x64 architecture, while my machine is ARM. By using the library BuildX for docker, I was able to compile the app for AMD64, which fixed the whole issue. `docker buildx build --platform linux/amd64 -t umarik/lexis . `

Now the application is available at: https://lexis404-4f4ah47qna-uc.a.run.app

I will be working on the Unit tests for Lexis now 👍

**Comment by zmtbnv** [comment]
Awesome work! Glad you figured it out :)

Now, you can try unit testing your python modules. When you need me to review your code, mention my name when you commit your changes. Will help you to better organize and test your app 👍🏻

**Comment by umartokyo** [comment]
I am in the process of studying unit tests. Just learned about mocking. Soon will finish reading unit testing with databases and create tests for Lexis.
